name: Build GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Build Wasm module
        run: wasm-pack build --target web
      - name: Copy files
        run: cp -r ./public ./pkg
      - name: Remove .gitignore
        run: rm ./pkg/.gitignore
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pkg